### ISSUE TITLE
Feature Request: теперь нужна отрисовка картиночек в комментариях

### ISSUE THREAD

**Issue by noremac09** [polina4096/voices#1]
![image](https://github.com/polina4096/voices/assets/25801549/50710d6b-94fd-44f6-ae4c-e4994dc2f4ff)
Получится такое завести отсюда: https://youtrack.jetbrains.com/issue/IDEA-332604 , чтобы окончательно всё было по канону?

**Comment by polina4096** [comment]
реализация должна быть сильно проще чем голосовых, попробую ^_^

**Comment by i582** [comment]
Кажется такое уже можно сделать через Rendered Documentation:
https://twitter.com/tagir_valeev/status/1703678620323999903

<img width="633" alt="Снимок экрана 2023-09-21 в 14 28 04" src="https://github.com/polina4096/voices/assets/51853996/9c0ec600-17b6-4e3f-ba65-87405be14eb9">

**Comment by polina4096** [comment]
угу, тогда закрываю

**Comment by Kamillaova** [comment]
![image](https://github.com/polina4096/voices/assets/54859825/16d22ec7-140e-4d18-ac00-c284bc3bfedd)
