### ISSUE TITLE
возможность хранить запись как текст вместо бинарных файлов

### ISSUE THREAD

**Issue by JMarkin** [polina4096/voices#15]
Добрый день, git нормально умеет работать с текстом, как предложение возможность хранить для озвучки не бинарные файлы записи голоса а конвертировать запись в текстовой вариант и озвучивать уже её?

**Comment by polina4096** [comment]
в случае если я правильно понимаю что вы предлагаете озвучивать текст условным TTS - нет. теряется вся суть голосовых сообщений, такой вариант не рассматриваю
