### ISSUE TITLE
Делать войсы свернутыми по умолчанию

### ISSUE THREAD

**Issue by MrAlejandro** [polina4096/voices#16]
Сделать любой войс по умолчанию "свернутым" и вместо него просто отображается надпись `Привет >`. 
Символ `>` означает что войс можно развернуть кликнув по нему.
При клике по `Привет >` — войс разворачивается, но не сразу, а со `sleep(10)` (значение в секундах). 
Пока sleep не закончится, нужно делать чтоб символ `>` поменялся на `.` затем на `..` затем на `...`, смена каждые 0.3 секунды, после `...` снова начинаем с `.` (и так по кругу). 

В дальнейшем можно так и с текстовыми комментами делать!

**Comment by polina4096** [comment]
что...

**Comment by aleqsunder** [comment]
О боже

**Comment by SnowVolf** [comment]
Дичь
