### ISSUE TITLE
Readme: how to use it after installation?

### ISSUE THREAD

**Issue by el-qq** [polina4096/voices#2]
Hi! 

IntelliJ IDEA 2023.2.2 (Ultimate Edition)
OS: Linux 6.5.3-1-MANJARO

Загружаю плагин, но дальше не могу понять как надо записывать voice messages
В readme бы обозначить куда идти, что нажимать после установки

**Comment by polina4096** [comment]
sorry for lack of any documentation

you can record a voice message using an action called "Record a voice message", which opens a small recording dialog. all voice messages are actually just comments that start with `voice:path_to_wav_file_from_project_root.wav`

there's also a gutter icon (similar to the one on rendered doc comments) which toggles regular and rendered voice message representations

you might need to restart the IDE after installation and have a working language support (e. g. code folding and doc comment rendering must work)

hope this helps

**Comment by el-qq** [comment]
Да, помогло, разобрался, спасибо большое! 

PS: плагин хорош  😎 🤌

**Comment by polina4096** [comment]
uh oh, i accidentally closed this while merging a pr

**Comment by Nikit4v** [comment]
Probably should move it to Wiki or README
