### ISSUE TITLE
Support voices in Python

### ISSUE THREAD

**Issue by pivasikpivtsakov** [polina4096/voices#22]
There are languages where comments start with `#`. This plugin currently starts comments with `//`, not depending on language. 
<img width="325" alt="image" src="https://github.com/polina4096/voices/assets/50816300/78edea01-8330-49b5-ab51-89e07cfa6167">

upd However, this works if edit comment manually:
`# // voice:.idea/1695466774714.wav`

**Comment by polina4096** [comment]
#23
