### ISSUE TITLE
Agree on a standard for voice comments

### ISSUE THREAD

**Issue by 0x501D** [polina4096/voices#26]
Greetings, I am the author of a similar [plugin](https://github.com/0x501D/vim-voice-comments) for vim and propose to agree on a standard for voice comments so that they are universal and work the same in different IDEs.

Currently I'm using this label:

```<comment (// | # | ...)> :voice="path_to file"```

Example:
```c
// :voice="~/stuff/bruh.ogg"
```
Using this lablel is easy to extract path with regexp:
```
'.* :voice="\(.*\)".*'
```

**Comment by polina4096** [comment]
i'm not sure there is any benefit in a format which is easy to parse with regexp

extensions that implement voice messages may most likely interact with LSP anyways to extract single line comments from sources to find where to insert graphics or add relevant interactions

there is no need to use regexp when the LSP already does the parsing

to me it feels that voice message comments should be represented as single line (not always possible: CSS) comments, so even if you really need to use regexp, it should be possible to parse all lines that follow the language-specific single line comment syntax with the current comment syntax


as of now, this extension uses: `voice:path_to_file` in a language specific single-line comment, it will be problematic to migrate to new, or support multiple formats

**Comment by 0x501D** [comment]
The main idea is not to simplify the use of regular expressions, but to agree on a single format.  I can change it to the `voice:path` format in my plugin without any problems.  the main thing is to agree on one format so that it works the same in different IDE's.

We can select the `voice:path` option in one line as a uniform format for presenting the voice comment.

**Comment by polina4096** [comment]
i do find it simpler to just agree on `voice:path` fromat to be completely honest, as i don't want to break compatibility with any possible existing comments, or support multiple formats

**Comment by 0x501D** [comment]
Agreed.  I will remake my plugin to the above format and stick to it.

**Comment by 0x501D** [comment]
I think we can close this issue.
