### ISSUE TITLE
Add bruuuh sound to README.md

### ISSUE THREAD

**Issue by okhsunrog** [polina4096/voices#5]
Adding bruuuh sound to demo.mp4 in README.md will significantly improve the satisfaction level of potential users of the extension. Using this sound is a well known pattern for improving the quality of memes. It can also  provide a continuous integration (CI) of the meme to dev community.
Link to the resource [BRUUUUH](https://www.youtube.com/watch?v=L31PnORleeQ)

**Comment by polina4096** [comment]
sure

**Comment by mxkmn** [comment]
Video has no sound 😥😓😭
