### ISSUE TITLE
Add record action to comment context menu

### ISSUE THREAD

**Issue by SnowVolf** [polina4096/voices#6]
![image](https://github.com/polina4096/voices/assets/14909737/b6d15659-9250-49d8-a027-202bf7e50472)
@polina4096 Currently, recording can be started only by selecting action through "Find action..." dialog. It's good idea to place this feature inside comment context menu

**Comment by polina4096** [comment]
oh, sure

**Comment by polina4096** [comment]
![image](https://github.com/polina4096/voices/assets/33405371/7e13e7d8-5e89-4521-9875-6664ff9ad7db)

**Comment by polina4096** [comment]
done
